### PR TITLE
Adds  New Building Block: Simple Stats List

### PR DESCRIPTION
**Pull request by brentswisher**
Adds a simple list for statistics, separated by horizontal rules. Optional classes to highlight positive or negative numbers with colors.

### CODE REVIEW

**Comment by rafibomb** [comment]
Sweet! I made some minor updates for you - looks good!

**Comment by rafibomb** [comment]
I added your GitHub too and added this to the dashboard kit.

screen shot 2017-04-25 at 1 16 37 pm

**Comment by rafibomb** [comment]
@brentswisher What's your twitter so we can give you a shoutout?

**Comment by brentswisher** [comment]
@rafibomb - Glad you liked it, I'm loving the building blocks. My twitter is brentswisher, thanks!

**Comment by rafibomb** [comment]
Excited to see more awesome Building Blocks you got! If you need suggestions, let me know!

**Comment by IamManchanda** [comment]
@brentswisher .... #159 might be just for you ....

**Comment by brentswisher** [comment]
@IamManchanda I could do that! Probably couldn't start till this weekend at the earliest though

**Comment by IamManchanda** [comment]
@brentswisher If you can complete till this weekend revert me and take that up!

cc / @canterberrie

**Pull request merged**
