### PR TITLE
[Counter]Plus Minus for changing value of Input(Number) field.

### PR DESCRIPTION
**Pull request by IamManchanda**
This adds a counter with plus minus buttons for changing value of Input(Number) field.

Credits: http://jsfiddle.net/laelitenetwork/puJ6G/

### CODE REVIEW

**Comment by IamManchanda** [comment]
Here is the quick codepen for the same too => http://codepen.io/IamManchanda/pen/zwrjXV

**Comment by rafibomb** [comment]
@IamManchanda Really good one! Since it is so similar in style to http://foundation.zurb.com/building-blocks/blocks/input-number-group.html

Can you change it too look like this instead? 
screen shot 2017-04-19 at 4 10 02 pm
or 
screen shot 2017-04-19 at 4 20 53 pm

**Comment by IamManchanda** [comment]
@rafibomb i can surely do this ... not a big issue for me.... 
but will this make sense .... to have two similar building blocks .
I think we should close this!

PS: Sorry .... i didn't knew similar was already added .... I will take care of this similarity thing from next PR's

**Comment by canterberrie** [comment]
@IamManchanda I still think it would be worth turning this into a Building Block if it looked a bit different. It's a cool piece! People will probably find it useful to have this in different forms.

**Comment by IamManchanda** [comment]
Ohk guys.... Changing it.... Thanks!

**Comment by rafibomb** [comment]
The functionality is great - and I think it's valuable to have 2 different styles for the same functionality.

**Comment by IamManchanda** [comment]
@rafibomb updated!

**Comment by rafibomb** [comment]
Woot! I adjusted the button padding a bit to make them rounder. Good work @IamManchanda !

**Pull request merged**
