### PR TITLE
browsersync can be returned as promise

### PR DESCRIPTION
**Pull request by paxperscientiam**
see title

### CODE REVIEW

**Comment by paxperscientiam** [comment]
@IamManchanda TY. Should i wait for @kball or merge?

**Comment by IamManchanda** [comment]
I will wait for kev!

**Comment by kball** [comment]
Hmm... after merging this finding browsersync is not working. Have verified it is related to the change to the server() function. Going to revert for now.

**Comment by paxperscientiam** [comment]
@kball Hey, sorry. I can see how this was premature / incomplete alteration.

**Pull request merged**
