### PR TITLE
Material Design Tabs

### PR DESCRIPTION
**Pull request by eli-townsend**
Material Design Tabs using only CSS and Kevin Ball's Mobile Nav Bar.

### CODE REVIEW

**Comment by IamManchanda** [comment]
Hey thanks for this @eli-townsend ... Heads down ... working on something else
But will see it soon!!

**Comment by IamManchanda** [comment]
Can this be an accordion on mobile @eli-townsend ??

See 
- http://foundation.zurb.com/sites/docs/responsive-accordion-tabs.html
- https://codepen.io/shehab-eltawel/pen/dYwOgX

**Comment by IamManchanda** [comment]
This file needs to be in Sass/Css typo
https://github.com/eli-townsend/building-blocks/blob/51d973cc07b2c14b09ffe47fbc920f7b6e1be727/src/building-blocks/material-design-tabs/material-design-tabs.scss

Taking this up from here...

**Comment by eli-townsend** [comment]
Can you elaborate on the focus bug?

**Comment by eli-townsend** [comment]
Is that what you meant by SASS/CSS typo?

**Comment by rafibomb** [comment]
Looks good - merged! Well done @eli-townsend !!

**Pull request merged**
