### PR TITLE
Closes #234, Added link tag to Topbar Center Logo

### LINKED ISSUE #234: Topbar Center Logo: Should the logo link to the index?
Should the logo be wrapped with a link to the site index here:
https://github.com/zurb/building-blocks/blob/master/src/building-blocks/topbar-center-logo/topbar-center-logo.html#L4

Isn´t that "best practice"? What do you think?

cc @IamManchanda

### PR DESCRIPTION
**Pull request by becandoo**
added link tag to [Topbar Center Logo](https://github.com/zurb/building-blocks/issues/234#issuecomment-307622602) as described in issue #234

### CODE REVIEW

**Comment by IamManchanda** [comment]
@becandoo Use `git commit --amend` and please update the title 
Suggestion => `Closes #234, Added link tag to Topbar Center Logo`

**Comment by IamManchanda** [comment]
After that use `git push -f origin issue-234` to fast forward the changes!

**Comment by becandoo** [comment]
I have changed the title as requested and ran 'git push -f origin issue-234'. Let me know if I need to do anything else. Thanks!

**Comment by kball** [comment]
Checking out the branch, I think it's fine. Merging

**Comment by IamManchanda** [comment]
**Great** wanted to be sure ... better to be safe then sorry so didnt wanted to merge :smile:

**Comment by IamManchanda** [comment]
Congrats @becandoo on your first time contribution :wink:

**Pull request merged**
