### PR TITLE
Closes #100 - Blockquotes!

### LINKED ISSUE #100: Create new BB: Block Quote
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** A simple block quote that within a body of text. Would be great to have a left-aligned, right-aligned, and full width block quote.  Use category "media" in the YML file.

**Example:** 
screen shot 2017-04-17 at 10 32 31 am

### PR DESCRIPTION
**Pull request by IamManchanda**
#100 
@canterberrie is this what you wanted ??

### CODE REVIEW

**Comment by canterberrie** [comment]
In the layout.html page, can you add some dummy text in there so that we can visualize how the block quotes will fit into a body of text? Essentially they should do what these [flexible images](https://github.com/zurb/building-blocks/pull/139) do, but with text. Thanks!

**Comment by IamManchanda** [comment]
See i am able to achieve this .... but as its nested into a callout .... I was able to do this with the normal grid system 

Grid system is so powerful and responsive so i though it was the best way to go about it... !

**Comment by canterberrie** [comment]
@IamManchanda hmm.. That's an interesting way to use block quotes, but what if the text next to the block quote is shorter than the text inside the block quote? Wouldn't that make the paragraph too short? 

I was thinking that the block quote could be placed between two paragraphs, and the paragraphs would wrap around the block quote (floated). This way, the user won't have to create a separate row each time they want to throw in a block quote.

**Comment by IamManchanda** [comment]
Sorry but I am out for the day christine... Gone to sleep... If there are any changes required today ... You will have to do yourself.... Good night!

**Comment by canterberrie** [comment]
@IamManchanda That's fine, thanks for all your building blocks!

**Comment by kball** [comment]
Merged! Great work @IamManchanda @canterberrie

**Pull request merged**
