### PR TITLE
This adds Neat Article Container

### PR DESCRIPTION
**Pull request by IamManchanda**
This looks to inspire from the simple, neat and clean **Medium** design 

**This includes Header, Image and Content Element**

PS: This is the best preview image i could provide .... if there is any updates required to preview image, please do the honours :smiling_imp:

### CODE REVIEW

**Comment by IamManchanda** [comment]
@rafibomb @canterberrie @kball 
Can anyone of you review on this ??
Thanks....

**Comment by rafibomb** [comment]
Wow - this is a really good one @IamManchanda - Can't wait till we can use Building Blocks inside of Building Blocks @kball ;)

**Comment by kball** [comment]
The technical challenge for referencing building blocks inside of building blocks is actually pretty small - the bigger challenge is the design problem. How do we specify & display these dependencies? @jkfcheng

**Comment by IamManchanda** [comment]
Also that color pallete PR matters a lot... I think we need to solve and close that soon @kball

**Pull request merged**
