### PR TITLE
Closes #130 - Added Wide Article Links

### LINKED ISSUE #130: Create new BB: Wide Article Link
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** A wide article link that ideally is used in a list (see example below). Should be super simple because this is meant to be a repeated item. 

**Include at least:** article name, author, short description, read more link, and thumbnail. 

Use category "media" in the YML file.

**Example taken from techcrunch.com:**
screen shot 2017-04-20 at 10 01 49 am

### PR DESCRIPTION
**Pull request by IamManchanda**
#130
Same like techcrunch, the heading gets the` $primary-color` on hover-focus

wide-article-link

### CODE REVIEW

**Comment by IamManchanda** [comment]
Poke @canterberrie for review

**Comment by rafibomb** [comment]
Nice use of button mixins @IamManchanda !

**Comment by IamManchanda** [comment]
Good to merge? @rafibomb

**Comment by rafibomb** [comment]
Made some tiny edits - merged! Don't worry - I got you!

**Comment by rafibomb** [comment]
@kball Can we get a deploy today?

**Pull request merged**
